/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.dsl.Interface;
import my.dsl.API.SpreadsheetApi;
import my.dsl.Game.Game;
import my.dsl.Parser.StringGrouping;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.input.KeyCode;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;


public class App extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        StringGrouping group = new StringGrouping();
        Game game = new Game();
        SpreadsheetApi api = new SpreadsheetApi();
        if (api.deleteSheet() == 200) {

            // Create a text input box
            TextField textField = new TextField();
            // Create a label
            Label label = new Label();
            label.setWrapText(true);

            ScrollPane scrollPane = new ScrollPane(label);
            scrollPane.setFitToWidth(true);
            scrollPane.setPrefHeight(400);

            // Create a VBox to hold the text input box and label
            VBox vbox = new VBox(10);
            vbox.getChildren().addAll(textField, scrollPane);
            VBox.setVgrow(scrollPane, Priority.ALWAYS);

            textField.setPromptText("Enter a string...");
            textField.setOnKeyPressed(event -> {
                if (event.getCode() == KeyCode.ENTER) {
                    // Update the label with the entered string
                    System.out.println("You entered: " + textField.getText());

                    // send input through to data structure
                    try {
                        group.update(textField.getText(), game);
                        label.setText("");
                        textField.setText("");
                        
                        if (api.deleteSheet() == 200) {
                            if (api.postGame(game)== 200) {
                                label.setText("Success");
                            }
                        }
                    } catch (Exception e1) {
                        if (e1.getMessage().equals("Input Format of DSL is Not Valid")) {
                            try {
                                label.setText(e1.getCause().getMessage() + getFileContent("/workspaces/Bbecker8-Artifact/my-dsl/app/src/main/java/my/dsl/Interface/NotValidDSL_text"));
                            } catch (Exception e2) {
                                e2.printStackTrace();
                            }
                        }
                        if (e1.getMessage().equals("Playtype not found")) {
                            try {
                                label.setText(e1.getCause().getMessage() + getFileContent("/workspaces/Bbecker8-Artifact/my-dsl/app/src/main/java/my/dsl/Interface/NotValidPlayType_text"));
                            } catch (Exception e2) {
                                e2.printStackTrace();
                            }
                        }
                        if (e1.getMessage().equals("Outcome did not match")) {
                            try {
                                label.setText(e1.getCause().getMessage() + getFileContent("/workspaces/Bbecker8-Artifact/my-dsl/app/src/main/java/my/dsl/Interface/NotValidOutcome_text"));
                            } catch (Exception e2) {
                                e2.printStackTrace();
                            }
                        }
                    }
                }
            });

            // Create a scene with the VBox
            Scene scene = new Scene(vbox, 500, 600);

            // Set the scene on the primary stage
            primaryStage.setScene(scene);
            primaryStage.setTitle("Text Input App");
            primaryStage.show();
        }
    }

    public static String getFileContent(String file) throws Exception{
    	try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;
            StringBuilder sb = new StringBuilder();
            while ((line = br.readLine()) != null) {
                sb.append(line);
                sb.append("\n"); // Add HTML line break tag
            }
            br.close();
            String labelText = sb.toString();

            // Set the text of the label with HTML formatting
            return labelText ;
        } catch (IOException e) {
            e.printStackTrace();
        }
		return null;
		
    }

}
